pipeline {
  agent any
  stages {
    stage('Checkout') {
       steps {
        sh 'echo passed'
        git branch: 'main', url: 'https://github.com/mallikarjunajethin/deploymnet-test.git'
      }
    }
    stage('Pull Docker Image') {
            environment {
			DOCKER_REGISTRY = 'mallikarjunajethin.jfrog.io/mallikarjunajethin-docker-local'
			IMAGE_NAME = 'maven-demo-docker'
			CREDENTIAL_ID = 'docker-hub-login'
		        DOCKER_HUB_URL= 'https://mallikarjunajethin.jfrog.io/'
               }
            steps {
                script {
                    // Login to the Docker registry using Jenkins credentials
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-login', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "docker login -u ${env.DOCKER_USERNAME} -p ${env.DOCKER_PASSWORD} ${env.DOCKER_HUB_URL}"
                        // pull the Docker image to the registry
                        sh "docker pull ${env.DOCKER_REGISTRY}/${env.IMAGE_NAME}:13"
                        }
                    }
                }
	     } 
    stage('Run Docker Container') {
            environment {
		DOCKER_REGISTRY = 'mallikarjunajethin.jfrog.io/mallikarjunajethin-docker-local'
		IMAGE_NAME = 'maven-demo-docker'
		CREDENTIAL_ID = 'docker-hub-login'
                CONTAINER_NAME = 'maven-demo'
                PORT_MAPPING = '8110:8180' // Example port mapping
                }
           steps {
                script {
                    // Run the Docker container
                    sh "docker run -d --name ${CONTAINER_NAME} -p ${PORT_MAPPING} ${env.DOCKER_REGISTRY}/${env.IMAGE_NAME}:13"
                }
            }

        }
	
   }
}
